### ISSUE TITLE
Support for bold links

### ISSUE THREAD

**Issue by marudy** [lappalj4/react-native-easy-markdown#25]
Support for links inside bold text is not there.

Provided PR #24

**Comment by zivester** [comment]
Hello.  I'm currently working on a team that has taken over maintenance of this project.  Could you try the new version and see if it works for you? `v1.3.0`, which has been relocated here: https://github.com/TitanInvest/react-native-easy-markdown

Just tested this and the following already should be supported:

```javascript
[**google.com**](https://www.google.com)
```

**Comment by winkelsdorf** [comment]
Could be closed, as `v1.3.0` supports bold text in links.

**Comment by marudy** [comment]
Tried it just today. Works well indeed along with another issue I faced and was the trigger to finally upgrade to this one. Thanks @zivester
